version: '3'
services:

  keycloack:
    image: quay.io/keycloak/keycloak:24.0.2
    command:
      - start-dev
      - --features=admin-fine-grained-authz
      - --features=token-exchange
      - --http-enabled=true
      - --https-port=8091
      - --https-certificate-file=/opt/keycloak/certs/keycloak-server.crt.pem
      - --https-certificate-key-file=/opt/keycloak/certs/keycloak-server.key.pem 
      - --verbose
    volumes:
      # Load the SSL certificates
      - ./certs:/opt/keycloak/certs
    environment:
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_ADMIN: admin
    networks:
      front-tier:
        ipv4_address: 172.16.212.18
    ports:
      - "8099:8080"
      - "8091:8091"

networks:
  front-tier:
    ipam:
      driver: default
      config:
        - subnet: "172.16.212.0/24"